version: '3.8'

services:
  proxy:
    image: traefik:latest
    restart: always
    ports:
      - "${DAEMON_PORT}:${DAEMON_PORT}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_DIR}/traefik/acme.json:/acme.json"
    environment:
      HETZNER_API_KEY: "${HETZNER_KEY}"
      TZ: "${TIMEZONE}"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:${DAEMON_PORT}"
      - "--certificatesresolvers.letsencrypt.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=hetzner"
  
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    env_file:
      - .env
    restart: always
    depends_on:
      - proxy
    ports:
      - "${SFTP_PORT}:${SFTP_PORT}"
    tty: true
    environment:
      TZ: "${TIMEZONE}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "${DATA_DIR}/wings/etc/:/etc/pterodactyl/"
      - "${DATA_DIR}/wings/logs:/var/log/pterodactyl/"
      - "${SERVERS_DIR}:${SERVERS_DIR}"
      # SSL Configuration: Uncomment one of the following lines based on your host system for HTTPS usage.
      # Uncomment this line if your host is based on Ubuntu/Debian:
      # - "/etc/ssl/certs:/etc/ssl/certs:ro"
      # Uncomment this line if your host is based on RHEL/Alma/Rocky/CentOS/Fedora:
      # - "/etc/ssl/certs/ca-certificates.crt:/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt:ro"
    labels:
      - "traefik.enable=true"
      # HTTPS Configuration 
      - "traefik.http.routers.wingssecure.entrypoints=websecure"
      - "traefik.http.routers.wingssecure.rule=Host(`${WINGS_DOMAIN}`)"
      - "traefik.http.routers.wingssecure.tls=true"
      - "traefik.http.routers.wingssecure.tls.certresolver=letsencrypt"
      - "traefik.http.services.wingssecure.loadbalancer.server.port=${DAEMON_PORT}"

networks:
  default:
    ipam:
      config:
        - subnet: 172.21.0.0/16
